scrolling = { history = 10000 , multiplier = 3}
mouse.hide_when_typing = true
mouse.bindings = [
    {mouse="Right", action="ExpandSelection"},
    {mouse="Right",mods="Control",action="Paste"},
    {mouse="Right", mods="Shift", action="ExpandSelection"}
]

[window.padding]
y = 5
x = 5

[[keyboard.bindings]]
key="v"
action="ToggleViMode"
mods="Control|Alt"

[font]
normal.family = "Monaspace Argon"
normal.style = "semibold"

[font.bold]
family = "Monaspace Neon"
style = "semibold"
[colors]
draw_bold_text_with_bright_colors = true

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'
