scrolling = { history = 10000, multiplier = 3 }

mouse.hide_when_typing = true
mouse.bindings = [
    { mouse = "Right", action = "ExpandSelection" },
    { mouse = "Right", mods = "Control", action = "Paste" },
    { mouse = "Right", mods = "Shift", action = "Copy" }
]

[window.padding]
y = 5
x = 5

[[keyboard.bindings]]
key = "v"
action = "ToggleViMode"
mods = "Control|Alt"

[[keyboard.bindings]]
key = "P"
mods = "Command"
action = "Paste"

[[keyboard.bindings]]
key = "Y"
mods = "Command"
action = "Copy"

[font]
normal.family = "Iosevka"
normal.style = "Regular"
size = 15

[font.bold]
family = "Iosevka"
style = "Regular"

# Night Owl Colors
[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '#011627'
foreground = '#d6deeb'

[colors.cursor]
cursor = '#d6deeb'
text = '#011627'

[colors.selection]
text = '#011627'
background = '#7fb1d6'

[colors.normal]
black   = '#011627'
red     = '#ef5350'
green   = '#22da6e'
yellow  = '#addb67'
blue    = '#82aaff'
magenta = '#c792ea'
cyan    = '#21c7a8'
white   = '#e6e6e6'

[colors.bright]
black   = '#575656'
red     = '#ff869a'
green   = '#3ad900'
yellow  = '#ffeb95'
blue    = '#a6ccff'
magenta = '#d6a8ff'
cyan    = '#7fdbca'
white   = '#ffffff'

[[colors.indexed_colors]]
index = 16
color = '#ecc48d'

[[colors.indexed_colors]]
index = 17
color = '#f78c6c'
